"""add_is_featured

Revision ID: 1c534661803a
Revises: e4023d29d3ee
Create Date: 2026-07-16 12:00:30.673428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c534661803a'
down_revision: Union[str, Sequence[str], None] = 'e4023d29d3ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio_item_versions', sa.Column('is_featured', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    op.add_column('portfolio_items', sa.Column('is_featured', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolio_items', 'is_featured')
    op.drop_column('portfolio_item_versions', 'is_featured')
    # ### end Alembic commands ###
