"""Initial migrations

Revision ID: e4023d29d3ee
Revises: 
Create Date: 2026-07-14 20:04:37.831273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4023d29d3ee'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatbot_knowledge',
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('question_or_keyword', sa.Text(), nullable=False),
    sa.Column('answer_context', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatbot_knowledge_id'), 'chatbot_knowledge', ['id'], unique=False)
    op.create_index(op.f('ix_chatbot_knowledge_is_deleted'), 'chatbot_knowledge', ['is_deleted'], unique=False)
    op.create_table('contact_messages',
    sa.Column('sender_name', sa.String(length=255), nullable=False),
    sa.Column('sender_email', sa.String(length=255), nullable=False),
    sa.Column('message_content', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_messages_id'), 'contact_messages', ['id'], unique=False)
    op.create_index(op.f('ix_contact_messages_is_deleted'), 'contact_messages', ['is_deleted'], unique=False)
    op.create_table('game_config_categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_config_categories_code'), 'game_config_categories', ['code'], unique=True)
    op.create_index(op.f('ix_game_config_categories_id'), 'game_config_categories', ['id'], unique=False)
    op.create_table('portfolio_sections',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('allowed_content_types', sa.JSON(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_sections_id'), 'portfolio_sections', ['id'], unique=False)
    op.create_index(op.f('ix_portfolio_sections_is_deleted'), 'portfolio_sections', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_portfolio_sections_name'), 'portfolio_sections', ['name'], unique=True)
    op.create_index(op.f('ix_portfolio_sections_slug'), 'portfolio_sections', ['slug'], unique=True)
    op.create_table('tags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_index(op.f('ix_tags_slug'), 'tags', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    op.create_table('game_configs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['game_config_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_configs_id'), 'game_configs', ['id'], unique=False)
    op.create_index(op.f('ix_game_configs_key'), 'game_configs', ['key'], unique=True)
    op.create_table('portfolio_items',
    sa.Column('section_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content_body', sa.Text(), nullable=True),
    sa.Column('custom_metadata', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['portfolio_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_items_id'), 'portfolio_items', ['id'], unique=False)
    op.create_index(op.f('ix_portfolio_items_is_deleted'), 'portfolio_items', ['is_deleted'], unique=False)
    op.create_table('media_items',
    sa.Column('portfolio_item_id', sa.Uuid(), nullable=False),
    sa.Column('cloudinary_public_id', sa.String(length=255), nullable=False),
    sa.Column('secure_url', sa.String(length=1024), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('file_format', sa.String(length=50), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_item_id'], ['portfolio_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_items_id'), 'media_items', ['id'], unique=False)
    op.create_index(op.f('ix_media_items_is_deleted'), 'media_items', ['is_deleted'], unique=False)
    op.create_table('portfolio_item_tags',
    sa.Column('portfolio_item_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_item_id'], ['portfolio_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('portfolio_item_id', 'tag_id')
    )
    op.create_table('portfolio_item_versions',
    sa.Column('portfolio_item_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content_body', sa.Text(), nullable=True),
    sa.Column('custom_metadata', sa.JSON(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['portfolio_item_id'], ['portfolio_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_item_versions_id'), 'portfolio_item_versions', ['id'], unique=False)
    op.create_index(op.f('ix_portfolio_item_versions_is_deleted'), 'portfolio_item_versions', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portfolio_item_versions_is_deleted'), table_name='portfolio_item_versions')
    op.drop_index(op.f('ix_portfolio_item_versions_id'), table_name='portfolio_item_versions')
    op.drop_table('portfolio_item_versions')
    op.drop_table('portfolio_item_tags')
    op.drop_index(op.f('ix_media_items_is_deleted'), table_name='media_items')
    op.drop_index(op.f('ix_media_items_id'), table_name='media_items')
    op.drop_table('media_items')
    op.drop_index(op.f('ix_portfolio_items_is_deleted'), table_name='portfolio_items')
    op.drop_index(op.f('ix_portfolio_items_id'), table_name='portfolio_items')
    op.drop_table('portfolio_items')
    op.drop_index(op.f('ix_game_configs_key'), table_name='game_configs')
    op.drop_index(op.f('ix_game_configs_id'), table_name='game_configs')
    op.drop_table('game_configs')
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tags_slug'), table_name='tags')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_portfolio_sections_slug'), table_name='portfolio_sections')
    op.drop_index(op.f('ix_portfolio_sections_name'), table_name='portfolio_sections')
    op.drop_index(op.f('ix_portfolio_sections_is_deleted'), table_name='portfolio_sections')
    op.drop_index(op.f('ix_portfolio_sections_id'), table_name='portfolio_sections')
    op.drop_table('portfolio_sections')
    op.drop_index(op.f('ix_game_config_categories_id'), table_name='game_config_categories')
    op.drop_index(op.f('ix_game_config_categories_code'), table_name='game_config_categories')
    op.drop_table('game_config_categories')
    op.drop_index(op.f('ix_contact_messages_is_deleted'), table_name='contact_messages')
    op.drop_index(op.f('ix_contact_messages_id'), table_name='contact_messages')
    op.drop_table('contact_messages')
    op.drop_index(op.f('ix_chatbot_knowledge_is_deleted'), table_name='chatbot_knowledge')
    op.drop_index(op.f('ix_chatbot_knowledge_id'), table_name='chatbot_knowledge')
    op.drop_table('chatbot_knowledge')
    # ### end Alembic commands ###
